# -*- coding: utf-8 -*-
"""Intelligent Text Summarization and Question Answering System using Transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KvQqKM1GlReqn9xskzpaSnB7opOBkrZ0
"""

!pip install transformers datasets torch sentencepiece

from transformers import T5Tokenizer, T5ForConditionalGeneration

model_name = "t5-small"
tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

from transformers import pipeline

qa_pipeline = pipeline(
    "question-answering",
    model="distilbert-base-uncased-distilled-squad",
    tokenizer="distilbert-base-uncased-distilled-squad"
)

text = input("Enter the text you want to summarize:\n")
input_text = "summarize: " + text

inputs = tokenizer.encode(input_text, return_tensors="pt", max_length=512, truncation=True)

summary_ids = model.generate(inputs, max_length=50, min_length=25, length_penalty=2.0, num_beams=4, early_stopping=True)
summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
print("Summary:", summary)

from transformers import pipeline

# Load QA pipeline
qa_pipeline = pipeline(
    "question-answering",
    model="distilbert-base-uncased-distilled-squad",
    tokenizer="distilbert-base-uncased-distilled-squad"
)

# Take input from user
context = input("Enter the context paragraph:\n")
question = input("Enter your question:\n")

# Get answer
result = qa_pipeline(question=question, context=context)
print("\nAnswer:\n", result['answer'])